<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260828102050 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Fix schema drift missed by past migrations: Version20260714172941 dropped the 3 individual '
            . 'messenger_messages indexes but never created the intended replacement composite index, and '
            . 'sale_payment_terminal_connection.provider / user_member.id / user_security_code.id never got '
            . 'migrations for their current mapping (default value and single-table-inheritance identity).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE sale_payment_terminal_connection ALTER provider SET DEFAULT \'sumup\'');

        // DROP IDENTITY also drops its backing sequence (Postgres identity sequences are owned by the
        // column), so a plain CREATE SEQUENCE ... START 1 afterwards would collide with existing rows on
        // the very next insert. We recreate the sequence and fast-forward it past the current max id.
        $this->addSql('ALTER TABLE user_member ALTER id DROP IDENTITY IF EXISTS');
        $this->addSql('CREATE SEQUENCE IF NOT EXISTS user_member_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql("SELECT setval('user_member_id_seq', COALESCE((SELECT MAX(id) FROM user_member), 1), (SELECT MAX(id) FROM user_member) IS NOT NULL)");

        $this->addSql('ALTER TABLE user_security_code ALTER id DROP IDENTITY IF EXISTS');
        $this->addSql('CREATE SEQUENCE IF NOT EXISTS user_security_code_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql("SELECT setval('user_security_code_id_seq', COALESCE((SELECT MAX(id) FROM user_security_code), 1), (SELECT MAX(id) FROM user_security_code) IS NOT NULL)");

        // Some environments already self-healed this via Messenger's DoctrineTransport auto_setup
        // (triggered by the app actually sending a message), so this must be idempotent.
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP INDEX IF EXISTS IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750');
        $this->addSql('ALTER TABLE sale_payment_terminal_connection ALTER provider DROP DEFAULT');

        // Mirror the same "don't restart at 1 under existing data" care as up(), via dynamic SQL since
        // RESTART WITH doesn't accept a subquery.
        $this->addSql('DROP SEQUENCE IF EXISTS user_member_id_seq CASCADE');
        $this->addSql('ALTER TABLE user_member ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql("DO $$ BEGIN EXECUTE format('ALTER TABLE user_member ALTER id RESTART WITH %s', COALESCE((SELECT MAX(id) FROM user_member), 0) + 1); END $$");

        $this->addSql('DROP SEQUENCE IF EXISTS user_security_code_id_seq CASCADE');
        $this->addSql('ALTER TABLE user_security_code ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql("DO $$ BEGIN EXECUTE format('ALTER TABLE user_security_code ALTER id RESTART WITH %s', COALESCE((SELECT MAX(id) FROM user_security_code), 0) + 1); END $$");
    }
}
